services: 
  php-cli:
    build:
      context: .
    image: php:8.3.10-cli-labo
    container_name: labo-php
    tty: true
    volumes:
      - "${LABO_PWD}:/labo:rw"
    entrypoint: |
      sh -c '
      set -e
      cd /labo
      if [ "$${1#-}" != "$$1" ]; then
        set -- php "$$@"
      fi
      exec "$$@"
      '
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2.0G

